platform:
  filename: "frame_0000.raw"
  disable_progress_bar: false
  leave_pbar_string: false
  render_3a: false
  # npy, png or both
  save_format: png

sensor_info:
  bayer_pattern: "gbrg"
  range: 65536
  bit_depth: 16
  width: 1920
  height: 1536
  output_bit_depth: 8

companding:
  is_enable: false
  input_range: 65535
  output_range: 1048575
  num_kneepoints: 10
  A: 87.6 # don't touch!
  is_save: false

crop:
  is_enable: false
  is_debug: false
  new_width: 1280
  new_height: 720
  is_save: false  

dead_pixel_correction: 
  is_enable: false
  dp_threshold: 80
  is_debug: true
  is_save: false

black_level_correction:
  is_enable: true
  r_offset: 256
  gr_offset: 256
  gb_offset: 256
  b_offset: 256
  is_linear: true
  r_sat: 1048570
  gr_sat: 1048570
  gb_sat: 1048570
  b_sat: 1048570
  is_save: false

oecf:
  is_enable: false
  # Make sure the LUT has the right bit range i.e. if image is of 10 bit LUT should be from [0 - (2^10)-1]
  # LUT here does nothing to the sensor response i.e. a value of 800 maps to 800 and 2000 maps to 2000  
  
  is_save: false

digital_gain:
  is_debug: true
  is_auto: true
  # Array of pre-define Gains
  gain_array: [1, 2, 4, 6, 8, 10, 12, 16, 32, 64]
  # Index of default gain
  current_gain: 1
  ae_feedback: 0
  is_save: false

lens_shading_correction: 
  is_enable: false
  is_save: false

bayer_noise_reduction:
  is_enable: true
  filter_window: 9
  r_std_dev_s: 1
  r_std_dev_r: 0.1
  g_std_dev_s: 1
  g_std_dev_r: 0.08
  b_std_dev_s: 1
  b_std_dev_r: 0.1
  is_save: false

auto_white_balance:
  is_enable: false
  is_debug: true
  underexposed_percentage: 0.01
  overexposed_percentage: 0.01
  algorithm: "pca"
  # grey_world, norm_2, pca
  percentage: 3.5 # pca

white_balance:
  is_enable: true
  # is_auto refers to auto white balance module
  is_debug: true
  is_auto: false
  r_gain: 1.17 #1.24609375
  b_gain: 1.2 #2.80859375
  is_save: false

demosaic:
  is_save: false

color_correction_matrix:
  #Row sum to 1 convention
  is_enable: true
  corrected_red: [1.660, -0.527, -0.133]
  corrected_green: [-0.408, 1.563, -0.082]
  corrected_blue: [-0.055, -1.641, 2.695]
  is_save: false

gamma_correction:
  is_enable: false

  

  is_save: false

auto_exposure:
  is_enable: true
  is_debug: true
  center_illuminance: 90
  histogram_skewness: 0.9

# Example usage in ISP pipeline
hdr_durant:
  is_enable: true
  is_save: True
  is_debug: True
  sigma_space: 10
  sigma_color: 0.4
  contrast_factor: 2
  downsample_factor: 4


color_space_conversion: 
  conv_standard: 2
  # Bt.709 HD =   1
  # Bt.601/4407 = 2
  is_save: false

color_saturation_enhancement:
  is_enable: true
  saturation_gain: 1.0


ldci:
  is_enable: true
  clip_limit: 1
  wind: 16
  is_save: false

sharpen:
  is_enable: false
  sharpen_sigma: 5
  sharpen_strength: 1
  is_save: false

2d_noise_reduction:
  is_enable: false
  # nlm
  window_size: 9
  patch_size: 5
  wts: 10
  is_save: false
  
rgb_conversion:
  is_enable: true
  is_save: false

scale:
  is_enable: false
  is_debug: true
  new_width: 1920
  new_height: 1080   
  is_hardware: true
  # Nearest_Neighbor # Bilinear
  algorithm: "Nearest_Neighbor"
  upscale_method: "Nearest_Neighbor"
  downscale_method: "Bilinear"  
  is_save: false

yuv_conversion_format:
  # The conversion wont run if csc is false
  is_enable: true
  conv_type: '444'
  is_save: false

